Tdd/backend
mjwwit/scrum-poker-server pull request #3
Opened 2019-12-13 09:41 UTC by HKiichi

adjusted the server side to include tdd (tests)

2019-12-17 19:44 UTC, mjwwit requested changes
Super nice werk! Ik heb nog wat kleine op- en aanmerkingen geplaatst maar dit ziet er heel goed uit!

2019-12-17 19:44 UTC, mjwwit commented on dist/src/helpers/RoomHelper.js
> +"use strict";
Ik zie dat deze files ondanks de toevoeging aan de `.gitignore` file toch in version control zijn gekomen. Je zal ze expliciet moeten verwijderen met `git rm` om ze er weer uit te krijgen.

2019-12-17 19:44 UTC, mjwwit commented on package.json
> +    "npm": "^6.13.4",
Het lijkt me sterk dat `npm` een dependency is.

2019-12-17 19:44 UTC, mjwwit commented on src/helpers/SchemeHelper.ts
> +        return cardScheme;
Het is in dit geval denk ik duidelijker en eenvoudiger om direct vanuit de `switch` `case`s te `return`en. Dit zorgt ervoor dat `cardScheme` en de `break` statements niet meer nodig zijn.

2019-12-17 19:44 UTC, mjwwit commented on src/models/CardScheme.ts
> +export interface CardScheme{
Ik zou deze `interface` niet exporten, maar ipv daarvan een union van alle implementaties exporten. Dat zorgt ervoor dat je gebruik kan maken van een tagged unions in andere delen van de code. Lees voor meer info [dit stukje](https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions).

2019-12-17 19:44 UTC, mjwwit commented on src/models/Room.ts
> +    id : any,
Is dit echt een `any`? Volgens mij wordt er een UUID v1 in gezet, in welk geval het een `string` is.

2019-12-17 19:44 UTC, mjwwit commented on src/models/RoomConfiguration.ts
> +    cardSchemeType: 'custom' | 'regular' | 'fibonacci',
Als je in het `CardScheme` model een tagged union maakt kan je hier `CardScheme['type']` gebruiken zodat je niet ieder type hier weer handmatig toe moet voegen.

2019-12-17 19:44 UTC, mjwwit commented on test/Room.test.ts
> +        return value++;
Een v1 UUID is een `string`, je kan hier eenvoudig een `string` returnen door `String(value++)` te returnen. Dit houdt de mock enigszins consistent met de realiteit.

2019-12-17 19:44 UTC, mjwwit commented on test/Room.test.ts
> +        let schemeHelperMock : any = createMock({type: "regular", scheme: [0, .5, 1, 2, 3, 5, 8, 13, 20]});
Kan dit geen `const` zijn?

2019-12-17 19:44 UTC, mjwwit commented on tsconfig.json
> +    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
Gezien dit een app is die door Node.js gedraait gaat worden is het niet nodig om zo'n lage compile target op te geven. `es2018` is geloof ik 100% ondersteund in de meest recente LTS van Node.js.

2019-12-17 19:44 UTC, mjwwit commented on tsconfig.json
> +    // "types": [],                           /* Type declaration files to be included in compilation. */
Ik zou hier `"types": ["node"],` van maken zodat je zonder specifieke imports alle types in `@types/node` beschikbaar hebt.

2020-01-08 10:22 UTC, HKiichi commented
Implemented the feedback

2020-01-08 10:22 UTC, closed without merging